# Irakli Sokhadze
**Tech Lead | Senior .NET Developer** 📍 Tbilisi, Georgia  
📞 598500860 | 📧 [irakli.sokhadze@outlook.com](mailto:irakli.sokhadze@outlook.com)  
🔗 [LinkedIn Profile](#) 

---

## 🚀 Professional Summary
Senior Software Engineer and Technical Lead with over **13 years of experience** in the banking and fintech industry. Specialist in modernizing legacy systems and decomposing monolithic architectures into scalable microservices. Proven track record in leading large teams using **Trunk-Based Development** and **"You Build It, You Run It"** principles. 

## 🛠 Technical Stack
| Category | Technologies |
| :--- | :--- |
| **Architecture** | Microservices, Monolith Decomposition, Trunk-Based Development, DevOps Culture |
| **Backend** | .NET Core, .NET Framework, C#, ASP.NET |
| **Data & Streaming** | Kafka, PostgreSQL, Oracle SQL |
| **Observability** | Kibana, ELK Stack |
| **Other** | JavaScript, Hardware-Software Integration (EV Chargers/Terminals) |

---

## 💼 Professional Experience

### **Space International** | *Technical Lead*
**December 2022 – Present**
- **Leadership:** Enforcing Trunk-Based Development and "You Build It, You Run It" principles for full software lifecycle ownership.
- **Modernization:** Spearheaded the decomposition of legacy monoliths into distributed microservices.
- **Architecture:** Designed event-driven architectures using **Kafka** and **PostgreSQL**.
- **Observability:** Integrated Kibana for real-time monitoring, significantly reducing incident response times.

### **Space International** | *Back End Developer*
**May 2021 – December 2022**
- Developed robust backend solutions for core banking and prepared systems for architectural transitions.

### **Project-Based** | *Technical Consultant*
- **TBC Bank & Grasen Integration:** Leading the integration of self-service terminals with EV chargers, bridging hardware protocols with banking software.

### **Liberty Bank** | *Senior Software Engineer*
**April 2019 – December 2022**
- Delivered critical software solutions and system optimizations for one of Georgia's largest commercial banks.

### **Terabank** | *Back End Developer*
**June 2014 – November 2018**
- Key role in backend development and maintenance for over 4 years.

---

## 🎓 Education
- **Tbilisi State University** *Bachelor of Applied Science (B.A.Sc.) – Computer Science* | 2010 – 2014

---
*Generated by [Your Name/GitHub]*
